name: Dev Pipeline

on:
  push:
    branches: ["staging"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Execute commands on EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEV_PATH }}
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            git stash && git pull
            pnpm i
            pm2 restart propmodel_rms || pm2 start ecosystem.config.cjs
